### ISSUE TITLE
cannot load such file

### ISSUE THREAD

**Issue by anishroff** [nicnocquee/imsticker#1]
I followed your instructions for installing things. But when I try to run command imsticker it says cannot load such file. Log is 

/Users/myusername/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- zip (LoadError)
    from /Users/myusername/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/myusername/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/lib/imsticker.rb:2:in `<top (required)>'
    from /Users/myusername/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/myusername/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/myusername/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/exe/imsticker:3:in`<top (required)>'
    from /Users/myusername/.rbenv/versions/2.3.1/bin/imsticker:23:in `load'
    from /Users/myusername/.rbenv/versions/2.3.1/bin/imsticker:23:in`<main>'

Any idea how to make this work ?

**Comment by anishroff** [comment]
After posting this I checked the details and wondered to install the gems which were required. It resolved the issues. Apologies for the trouble.

**Comment by anishroff** [comment]
Some how again it stuck at below location it says

/Users/Janak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/lib/imsticker.rb:240:in `block (2 levels) in download_template': uninitialized constant Zip::File (NameError)
Did you mean?  File
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/lib/imsticker.rb:237:in`open'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/lib/imsticker.rb:237:in `block in download_template'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/2.3.0/open-uri.rb:155:in`open_uri'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/2.3.0/open-uri.rb:717:in `open'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/2.3.0/open-uri.rb:35:in`open'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/lib/imsticker.rb:235:in `download_template'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/lib/imsticker.rb:31:in`generate'
    from /Users/Janak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/imsticker-0.1.7/exe/imsticker:9:in `<top (required)>'
    from /Users/Janak/.rbenv/versions/2.3.1/bin/imsticker:23:in`load'
    from /Users/Janak/.rbenv/versions/2.3.1/bin/imsticker:23:in `<main>'

Any idea how to resolve this ?

**Comment by nicnocquee** [comment]
Seems like it failed to download the Xcode template. Can you check the content of `/Users/<user>/.imsticker/template`? 

There should be the following files

```
nico@~:$ ls -la ~/.imsticker/template/
total 16
drwxr-xr-x  7 nico  staff   238 Jul 31 23:53 .
drwxr-xr-x  3 nico  staff   102 Jul 31 23:53 ..
-rw-r--r--  1 nico  staff  1403 Jul 31 23:53 .gitignore
drwxr-xr-x  4 nico  staff   136 Jul 31 23:53 Awesome Stickers.xcodeproj
drwxr-xr-x  4 nico  staff   136 Jul 31 23:53 StickerPackExtension
drwxr-xr-x  3 nico  staff   102 Jul 31 23:53 TestStickers
-rw-r--r--  1 nico  staff     1 Jul 31 23:53 version
```

The script basically downloads the project template from [this repo](https://github.com/nicnocquee/iOStickersTemplate) to `/Users/<user>/.imsticker/template` directory if not exists yet.

**Comment by bennettrogers** [comment]
The `uninitialized constant Zip::File` error happens if the `zip` gem is installed instead of the `rubyzip` gem. I had these same errors after manually installing dependencies.

This could probably be fixed by specifying the correct dependencies in `imsticker.gemspec`. As far as I can tell, those dependencies are `rubyzip` and `image_resizer`.
